apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lbfau98ce-nodejs 
  janus-idp.io/tekton: lbfau98ce-nodejs
  backstage.io/kubernetes-id: lbfau98ce-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lbfau98ce-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  